### ISSUE TITLE
osgi-run Version update

### ISSUE THREAD

**Issue by fredzqm** [renatoathaydes/osgi-run-tutorial#1]
Hi Renato,
Great work on the tutorial. I really appreciate it.
When I run it today with `gradle 4.1`, it seems to be broken

```
> Configure project :
The Task.leftShift(Closure) method has been deprecated and is scheduled to be removed in Gradle 5.0. Please use Task.doLast(Action) instead.


FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':cleanOsgiRuntime'.
> Unable to delete file: C:\Users\zhang\Documents\EclipseWorkspace\CSSE477\osgi-run-tutorial\build\osgi\felix-cache\bundle1\version0.0\bundle.jar

```

Those were easily fixed by upgrading the 

```
    id "com.athaydes.osgi-run" version "1.5.0"
```
To
```
    id "com.athaydes.osgi-run" version "1.5.5"
```

**Comment by renatoathaydes** [comment]
Ah, ok, thanks for letting me know.... I will update.

**Comment by renatoathaydes** [comment]
I added a note in the tutorial that the version should be updated to the latest, with a link to the latest version so I don't need to update it for every new release.

https://sites.google.com/a/athaydes.com/renato-athaydes/posts/osgi-runtutorial-runyourjavakotlinfregecodeinosgi
